"use client";
import { useState } from "react";
import Link from "next/link";
import { Building2, Users, CircleCheck, Hourglass, Download, User, School, ArrowRight, ChevronDown, Archive, Search } from "lucide-react";
import { STAGES, downloadFile, initials } from "@/lib/admissions-data";
import { AdmissionsShell, Badge, Footer, NewApplication, SelectFilter, useAdmissions, ViewSwitch } from "./admissions-shared";
export function AdmissionsPipeline() {
    const { applicants } = useAdmissions();
    const [year, setYear] = useState("All year groups");
    const [round, setRound] = useState("All rounds");
    const [priority, setPriority] = useState("All criteria");
    const [search, setSearch] = useState("");
    const [archive, setArchive] = useState(false);
    const filtered = applicants.filter(a => (year === "All year groups" || a.year === year) && (round === "All rounds" || a.route === round) && (priority === "All criteria" || `Priority ${a.priority}` === priority) && `${a.name} ${a.id}`.toLowerCase().includes(search.toLowerCase()));
    const active = applicants.filter(a => !["Withdrawn", "Declined"].includes(a.stage));
    const accepted = applicants.filter(a => ["Accepted", "Enrolled"].includes(a.stage)).length;
    return <AdmissionsShell current="Admissions pipeline"><header className="adm-page-heading"><div><div className="adm-inline"><Badge tone="brand">PAN 180</Badge><Badge>2025–2026 intake</Badge></div><h1>Admissions Pipeline &amp;<br className="adm-desktop-break"/> Intake Management</h1><p>Year 7 normal round &amp; in-year transfers · Coordinated LA scheme</p></div><div className="adm-heading-actions"><ViewSwitch /><div className="adm-inline"><button className="adm-button" onClick={() => downloadFile("admissions-pipeline.csv", "Reference,Applicant,Stage\n" + filtered.map(a => [a.id, a.name, a.stage].map(value => `"${value.replaceAll('"', '""')}"`).join(",")).join("\n"), "text/csv")}><Download />Export pipeline</button><NewApplication /></div></div></header>
 <section className="adm-filter-panel" aria-label="Pipeline filters"><div className="adm-inline"><SelectFilter label="Cohort" value={year} onChange={setYear} options={["All year groups", "Year 7", "Year 8", "Year 12"]}/><SelectFilter label="Round" value={round} onChange={setRound} options={["All rounds", "Normal round", "In-year transfer"]}/><SelectFilter label="Criteria" value={priority} onChange={setPriority} options={["All criteria", "Priority 1", "Priority 2", "Priority 3", "Priority 4"]}/><label className="adm-search"><Search /><input aria-label="Search candidates" placeholder="Find a candidate…" value={search} onChange={e => setSearch(e.target.value)}/></label></div><p className="adm-muted">Showing {filtered.length} demonstration candidates <button className="adm-text-button" onClick={() => { setYear("All year groups"); setRound("All rounds"); setPriority("All criteria"); setSearch(""); }}>Reset filters</button></p></section>
 <div className="adm-stats"><div className="adm-stat"><Building2 /><span>Total intake capacity (PAN)</span><strong>180 <small>places published</small></strong><p>Year 7 · Standard secondary intake</p></div><div className="adm-stat"><Users /><span>Active applications</span><strong>{active.length} <Badge tone="brand">Demo cohort</Badge></strong><p>Normal round &amp; direct school applications</p></div><div className="adm-stat"><CircleCheck /><span>Offers accepted</span><strong>{accepted} <small>/ 180 places</small></strong><progress value={accepted} max={180}/><p>{180 - accepted} places remaining in demo</p></div><div className="adm-stat"><Hourglass /><span>Awaiting verification</span><strong>{applicants.filter(a => a.stage === "Documents Pending").length}</strong><p>SIF evidence &amp; address documents</p></div></div>
 <div className="adm-board-hint"><h2>Admissions pathway</h2><span>Scroll across to see all seven stages <ArrowRight /></span></div><div className="adm-board" tabIndex={0} aria-label="Admissions pipeline, scroll horizontally to view all stages">{STAGES.map((stage, i) => { const items = filtered.filter(a => a.stage === stage); return <section className="adm-lane" key={stage}><header><span className={`adm-stage-dot stage-${i}`}/><h3>{i + 1}. {stage}</h3><Badge>{items.length}</Badge></header><div className="adm-lane-cards">{items.map(a => <Link href={`/admissions/applications/${a.id}`} className="adm-candidate" key={a.id}><div className="adm-candidate-title"><span className="adm-avatar small">{initials(a.name)}</span><Badge tone={a.priority === "1" ? "success" : a.stage === "Documents Pending" ? "warning" : "brand"}>{a.stage === "Documents Pending" ? "Action required" : `Priority ${a.priority}`}</Badge></div><h4>{a.name}</h4><p>{a.id} · {a.year}</p><div className="adm-candidate-note">{a.note}</div><p className="adm-icon-line"><User />{a.parent}</p><p className="adm-icon-line"><School />{a.school}</p><div className="adm-candidate-bottom"><span>{a.route}</span><span>View dossier <ArrowRight /></span></div></Link>)}{!items.length && <div className="adm-lane-empty">No candidates in this stage</div>}</div></section>; })}</div>
 <section className="adm-archive"><button aria-expanded={archive} onClick={() => setArchive(!archive)}><Archive /><div><strong>Declined &amp; withdrawn applications</strong><p>Archived records and changes to the intake</p></div><Badge>{filtered.filter(a => ["Withdrawn", "Declined"].includes(a.stage)).length} cases</Badge><ChevronDown className={archive ? "adm-rotated" : ""}/></button>{archive && <div className="adm-archive-content">{filtered.filter(a => ["Withdrawn", "Declined"].includes(a.stage)).map(a => <Link key={a.id} href={`/admissions/applications/${a.id}`}><strong>{a.name}</strong><Badge>{a.stage}</Badge><p>{a.note}</p></Link>)}{!filtered.some(a => ["Withdrawn", "Declined"].includes(a.stage)) && <p>No archived applications match your filters.</p>}</div>}</section><Footer /></AdmissionsShell>;
}
