"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowUpDown, ChevronLeft, ChevronRight, Download, Search, MapPin, Printer, CheckCheck } from "lucide-react";
import { STAGES, formatDate, initials, downloadFile } from "@/lib/admissions-data";
import { AdmissionsShell, Footer, NewApplication, SelectFilter, StageBadge, useAdmissions, ViewSwitch } from "./admissions-shared";
export function ApplicationsList() {
    const { applicants, save } = useAdmissions();
    const [tab, setTab] = useState("All applications");
    const [search, setSearch] = useState("");
    const [year, setYear] = useState("All year groups");
    const [stage, setStage] = useState("All stages");
    const [date, setDate] = useState("");
    const [page, setPage] = useState(1);
    const [perPage, setPerPage] = useState("8");
    const [selected, setSelected] = useState<string[]>([]);
    const [ascending, setAscending] = useState(false);
    const [notice, setNotice] = useState("");
    const filtered = applicants.filter(a => (tab === "All applications" || tab === "Normal round" && a.route === "Normal round" || tab === "In-year transfers" && a.route === "In-year transfer" || tab === "Action required" && a.stage === "Documents Pending" || tab === "Withdrawn" && a.stage === "Withdrawn") && (year === "All year groups" || a.year === year) && (stage === "All stages" || a.stage === stage) && (!date || a.date >= date) && `${a.name} ${a.id} ${a.parent}`.toLowerCase().includes(search.toLowerCase()));
    if (ascending)
        filtered.sort((a, b) => a.name.localeCompare(b.name));
    const pages = Math.max(1, Math.ceil(filtered.length / Number(perPage)));
    const current = Math.min(page, pages);
    const visible = filtered.slice((current - 1) * Number(perPage), current * Number(perPage));
    const reset = () => { setSearch(""); setYear("All year groups"); setStage("All stages"); setDate(""); setTab("All applications"); setPage(1); setSelected([]); };
    const exportCsv = () => { const records = selected.length ? filtered.filter(a => selected.includes(a.id)) : filtered; const cell = (v: string) => `"${v.replaceAll('"', '""')}"`; downloadFile("admissions-register.csv", ["Reference,Applicant,Year,Parent,Stage,Priority", ...records.map(a => [a.id, a.name, a.year, a.parent, a.stage, a.priority].map(cell).join(","))].join("\n"), "text/csv"); };
    return <AdmissionsShell current="Applications list"><header className="adm-page-heading"><div><h1>Admissions Applications<br /> Register</h1><p>Search and administer applications, entry cohorts and admissions criteria.</p></div><div className="adm-heading-actions"><ViewSwitch list/><div className="adm-inline"><button className="adm-button" onClick={exportCsv}><Download />Export register (CSV)</button><NewApplication /></div></div></header>
 <div className="adm-stats compact">{[["PAN capacity (Y7)", "180", "Published places"], ["Total submissions", String(applicants.length), "Demonstration applications"], ["Offers accepted", String(applicants.filter(a => ["Accepted", "Enrolled"].includes(a.stage)).length), "Confirmed places"], ["Awaiting verification", String(applicants.filter(a => a.stage === "Documents Pending").length), "SIF & address proofs"]].map(([title, value, sub]) => <div className="adm-stat" key={title}><span>{title}</span><strong>{value}</strong><p>{sub}</p></div>)}</div>
 <section className="adm-register"><div className="adm-tabs" role="tablist" aria-label="Application groups">{["All applications", "Normal round", "In-year transfers", "Action required", "Withdrawn"].map(t => <button key={t} role="tab" aria-selected={tab === t} onClick={() => { setTab(t); setPage(1); setSelected([]); }}>{t}</button>)}</div><div className="adm-register-filters"><label className="adm-search"><Search /><input aria-label="Search applications" placeholder="Search name, reference or parent…" value={search} onChange={e => { setSearch(e.target.value); setPage(1); setSelected([]); }}/></label><SelectFilter label="Entry" value={year} onChange={v => { setYear(v); setPage(1); setSelected([]); }} options={["All year groups", "Year 7", "Year 8", "Year 12"]}/><SelectFilter label="Status" value={stage} onChange={v => { setStage(v); setPage(1); setSelected([]); }} options={["All stages", ...STAGES, "Withdrawn", "Declined"]}/><label className="adm-filter"><span>Applied from</span><input type="date" value={date} onChange={e => { setDate(e.target.value); setPage(1); setSelected([]); }}/></label><button className="adm-text-button" onClick={reset}>Reset</button></div><div className="adm-register-caption"><span>Active view: <strong>{tab}</strong> · 2025–2026 intake</span><button className="adm-text-button" onClick={() => window.print()}><Printer />Print register</button></div>
 <div className="adm-table-wrap"><table className="adm-table"><thead><tr><th><input type="checkbox" aria-label="Select visible applications" checked={visible.length > 0 && visible.every(a => selected.includes(a.id))} onChange={e => setSelected(e.target.checked ? [...new Set([...selected, ...visible.map(a => a.id)])] : selected.filter(id => !visible.some(a => a.id === id)))}/></th><th><button onClick={() => setAscending(!ascending)}>Applicant details <ArrowUpDown /></button></th><th>Reference &amp; type</th><th>Entry cohort</th><th>Parent / carer &amp; location</th><th>Admissions criteria</th><th>Status</th><th><span className="sr-only">View application</span></th></tr></thead><tbody>{visible.map(a => <tr key={a.id}><td><input type="checkbox" aria-label={`Select ${a.name}`} checked={selected.includes(a.id)} onChange={e => setSelected(e.target.checked ? [...selected, a.id] : selected.filter(id => id !== a.id))}/></td><td><Link className="adm-person" href={`/admissions/applications/${a.id}`}><span className="adm-avatar">{initials(a.name)}</span><span><strong>{a.name}</strong><small>{formatDate(a.dob)} · {a.school}</small></span></Link></td><td><strong>{a.id}</strong><small>{a.route} (1st preference)</small></td><td><strong>{a.year}</strong><small>Autumn term 2025</small></td><td><strong>{a.parent}</strong><small>{a.email}</small><small className="adm-icon-line"><MapPin />{a.postcode} · {a.distance} miles</small></td><td><strong>Priority {a.priority}</strong><small>{a.note}</small></td><td><StageBadge stage={a.stage}/></td><td><Link aria-label={`View ${a.name}`} href={`/admissions/applications/${a.id}`}><ChevronRight size={18}/></Link></td></tr>)}</tbody></table>{!visible.length && <div className="adm-empty"><Search /><h2>No applications found</h2><p>Try another name or clear your filters.</p><button className="adm-button" onClick={reset}>Clear filters</button></div>}</div>
 <div className="adm-pagination"><span>Showing {filtered.length ? (current - 1) * Number(perPage) + 1 : 0}–{Math.min(current * Number(perPage), filtered.length)} of <strong>{filtered.length}</strong> applications</span><SelectFilter label="Rows" value={perPage} onChange={v => { setPerPage(v); setPage(1); }} options={["8", "16", "24"]}/><div><button className="adm-button" disabled={current === 1} onClick={() => setPage(current - 1)}><ChevronLeft />Previous</button><span>{current} / {pages}</span><button className="adm-button" disabled={current === pages} onClick={() => setPage(current + 1)}>Next<ChevronRight /></button></div></div></section>
 <div className="adm-bulk"><span>{selected.length ? `${selected.length} applications selected` : "Select applications to perform a coordinated action."}</span><button className="adm-button" disabled={!selected.length} onClick={exportCsv}><Download />Export selected</button><button className="adm-button primary" disabled={!selected.length} onClick={() => { const eligible = selected.filter(id => applicants.some(a => a.id === id && a.stage === "Review")); try {
        save(applicants.map(a => eligible.includes(a.id) ? { ...a, stage: "Offered" } : a));
        setNotice(`${eligible.length} demo offers recorded. Only applications at Review can be offered. No letters have been sent.`);
        setSelected([]);
    }
    catch {
        setNotice("Changes could not be saved. Browser storage may be full.");
    } }}><CheckCheck />Record offers</button></div>{notice && <p className="adm-notice" role="status">{notice}</p>}<Footer /></AdmissionsShell>;
}
