"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, FileText, Download, Pencil, MapPin, Phone, Mail, ShieldCheck, LockKeyhole, Upload, GraduationCap, AlertTriangle } from "lucide-react";
import { STAGES, formatDate, initials, downloadFile } from "@/lib/admissions-data";
import { AdmissionsShell, Badge, Footer, Panel, StageBadge, useAdmissions } from "./admissions-shared";
export function ApplicationDossier({ id }: {
    id: string;
}) {
    const { applicants, save } = useAdmissions();
    const a = applicants.find(x => x.id === id);
    const [note, setNote] = useState("");
    const [notes, setNotes] = useState<string[]>([]);
    const [uploads, setUploads] = useState<string[]>([]);
    const [notice, setNotice] = useState("");
    if (!a)
        return <AdmissionsShell current="Application not found"><div className="adm-empty"><h1>Application not found</h1><p>This reference is not in the demo register.</p><Link className="adm-button" href="/admissions/applications">Return to applications</Link></div></AdmissionsShell>;
    const index = STAGES.indexOf(a.stage as typeof STAGES[number]);
    const reference = id.startsWith("CAF-");
    const documents = reference ? ["CAF submission form", "Supplementary information form (SIF)", "Proof of address"] : [];
    const move = (stage: typeof a.stage) => { try {
        save(applicants.map(x => x.id === id ? { ...x, stage } : x));
        setNotice(`Application moved to ${stage}. This change is saved locally.`);
    }
    catch {
        setNotice("Unable to save. Please allow browser storage and try again.");
    } };
    return <AdmissionsShell current={`${a.name} (${a.id})`}><section className="adm-dossier-summary"><div className="adm-summary-top"><div className="adm-person"><span className="adm-avatar large">{initials(a.name)}</span><div><h1>{a.name}</h1><StageBadge stage={a.stage}/><p><strong>{a.id}</strong> <span>· DOB: {formatDate(a.dob)} · {a.year}</span></p><p className="adm-icon-line"><GraduationCap />Previous school: {a.school}</p><p className="adm-icon-line adm-success-text"><ShieldCheck />Local authority: Durham County Council</p></div></div><div className="adm-inline"><Link className="adm-button" href={`/admissions/applications/${id}/edit`}><Pencil />Edit</Link><button className="adm-button" onClick={() => window.print()}><Download />Print / PDF</button><button className="adm-button primary" disabled={a.stage !== "Review"} onClick={() => move("Offered")}><Mail />Record offer</button></div></div><div className="adm-criteria-banner"><ShieldCheck /><div>Admissions criterion applied: <strong>Priority {a.priority} — {a.priority === "1" ? "Looked-after children" : a.priority === "2" ? "Sibling connection" : a.priority === "3" ? "Church of England / faith affiliation" : "Residential proximity"}</strong><p>{a.note} · Distance: <strong>{a.distance} miles</strong></p></div></div><div className="adm-pathway-heading"><span>Statutory admissions pathway</span><button className="adm-text-button" disabled={a.stage === "Withdrawn"} onClick={() => { if (window.confirm(`Withdraw ${a.name}’s demo application?`))
        move("Withdrawn"); }}>Withdraw application</button></div><ol className="adm-pathway">{STAGES.map((s, i) => <li key={s} className={i < index ? "complete" : i === index ? "current" : ""}><span>{i + 1}. {s}{i < index && <CheckCircle2 />}</span><small>{i < index ? "Completed" : i === index ? "Current stage" : "Upcoming"}</small></li>)}</ol></section>
 {notice && <div role="status" className="adm-notice">{notice}</div>}<div className="adm-dossier-grid"><div className="adm-stack"><Panel title="Intended Admission & Academic Placement" aside={<Badge>2025/2026 intake</Badge>}><dl className="adm-facts"><div><dt>Intended cohort / key stage</dt><dd>{a.year} ({a.year === "Year 12" ? "Key Stage 5" : "Key Stage 3"})</dd></div><div><dt>Proposed enrolment date</dt><dd>{formatDate(a.start || "2025-09-03")} (Autumn term)</dd></div><div><dt>Admission round route</dt><dd>{a.route} · Coordinated secondary round</dd></div><div><dt>Coordinating local authority</dt><dd>Durham County Council (LEA 840)</dd></div></dl>{a.priority === "2" || id === "CAF-2025-0145" ? <div className="adm-info-block"><span className="adm-avatar small">{id === "CAF-2025-0145" ? "GO" : "SC"}</span><div><strong>{id === "CAF-2025-0145" ? "Grace O’Connor" : "Sibling connection"}</strong><Badge tone={reference ? "success" : "warning"}>{reference ? "Confirmed on roll" : "Verification required"}</Badge><p>{id === "CAF-2025-0145" ? "Sister · Year 9 · Bede House / Form 9B" : a.note}</p></div></div> : <p className="adm-muted">No sibling connection recorded.</p>}</Panel>
 <Panel title="Parent / Carer Details & Residency" aside={<Badge tone={reference ? "success" : "warning"}>{reference ? "Address verified" : "Address awaiting verification"}</Badge>}><div className="adm-contact"><div className="adm-inline"><span className="adm-number">1</span><strong>{a.parent}</strong><Badge>Primary contact</Badge></div><div className="adm-contact-links"><a href={`tel:${a.phone}`}><Phone />{a.phone}</a><a href={`mailto:${a.email}`}><Mail />{a.email}</a></div><p className="adm-icon-line"><MapPin />{a.address || "18 St. Cuthbert’s Way, Durham, County Durham"}, {a.postcode}</p><small>Straight-line distance to academy main gate: {a.distance} miles</small></div>{id === "CAF-2025-0145" && <div className="adm-contact"><div className="adm-inline"><span className="adm-number">2</span><strong>Roisin O’Connor</strong><Badge>Mother</Badge></div><p>07700 900812 · Same as primary residence</p></div>}</Panel>
 <Panel title="Special Provisions, Inclusion & Welfare" aside={<Badge>Demo information</Badge>}>{id === "CAF-2025-0145" ? <div className="adm-welfare"><div><strong>Pupil Premium (PP)</strong><Badge tone="success">Eligible (FSM Ever 6)</Badge><p>Eligibility recorded in the supplied applicant reference. Verification required before enrolment.</p></div><div><strong>SEND support</strong><Badge tone="brand">{a.send || "SEN support (K)"}</Badge><p>Primary need: Specific learning difficulty. Classroom adjustments to be confirmed with the SENCO.</p></div><div><strong>Medical &amp; dietary</strong><p>{a.medical || "No medical conditions recorded."}</p></div></div> : <dl className="adm-facts"><div><dt>SEND provision</dt><dd>{a.send || "Not recorded"}</dd></div><div><dt>Medical &amp; access requirements</dt><dd>{a.medical || "Not recorded"}</dd></div></dl>}<p className="adm-muted">Illustrative welfare details for this design preview.</p></Panel></div>
 <div className="adm-stack"><Panel title="Criteria Assessment" aside={<Badge>Oversubscription</Badge>}><div className="adm-assessment"><div className="adm-inline"><span>Assigned criteria band</span><strong>Priority {a.priority}</strong></div><p>{a.note}</p>{a.faith === "Yes" && <p>{a.denomination} · {a.parish} · {a.minister}</p>}<hr /><div className="adm-inline"><span>Tie-break distance</span><strong>{a.distance} miles (direct)</strong></div></div>{a.stage === "Documents Pending" && <div className="adm-warning"><AlertTriangle /><p>Admissions review on hold: the outstanding evidence must be received before progressing.</p></div>}</Panel>
 <Panel title="Statutory Documents" aside={<Badge tone={uploads.length ? "success" : "warning"}>{uploads.length ? "Selected this session" : reference ? "1 outstanding" : "Not verified"}</Badge>}>{documents.map(d => <div className="adm-document" key={d}><FileText /><div><strong>{d}</strong><small>Reference record · example document</small></div><button className="adm-icon-button" aria-label={`Download ${d} sample`} onClick={() => downloadFile(`${d}.txt`, `DEMONSTRATION DOCUMENT\n${d}\nApplicant: ${a.name}\nReference: ${id}\nThis is a sample record, not an original statutory document.`)}><Download /></button></div>)}<div className="adm-upload-panel"><strong>Baptism certificate / supporting evidence</strong><p>{uploads.length ? uploads.join(", ") : "Clergy signature or supporting document required."}</p><label className="adm-button primary"><Upload />Choose document<input className="sr-only" type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e => { const f = e.target.files?.[0]; if (f) {
        if (f.size > 10 * 1024 * 1024) {
            setNotice("Choose a document smaller than 10 MB.");
            return;
        }
        setUploads([...uploads, f.name]);
        setNotice(`${f.name} selected for this preview. File contents are not uploaded or stored.`);
    } }}/></label><small>PDF or image · up to 10 MB · session preview only</small></div></Panel>
 <Panel title="Admissions Chronology" aside={<span className="adm-muted">{reference ? 3 : 2} events logged</span>}><ol className="adm-timeline"><li><strong>Application status: {a.stage}</strong><p>{a.note}</p></li>{reference && <li><strong>Proof of address recorded</strong><small>10/10/2024 · 11:05</small><p>Residency details recorded by the admissions registrar.</p></li>}<li><strong>Application received</strong><small>{formatDate(a.date)} · 09:15</small><p>{a.route} · {a.school}</p></li></ol></Panel>
 <Panel title="Confidential Committee Notes" aside={<LockKeyhole size={16}/>}>{reference && <div className="adm-note"><strong>Admissions Officer</strong><small>11/10/2024 · 10:14</small><p>{a.note}. Follow up with the primary contact before the next review.</p></div>}{notes.map((n, i) => <div className="adm-note" key={i}><strong>Dr. Rachel Holloway</strong><p>{n}</p></div>)}<label className="adm-field">Add an internal admissions note<textarea placeholder="Record correspondence, checks or review notes…" value={note} onChange={e => setNote(e.target.value)} rows={3}/></label><div className="adm-inline adm-note-action"><small>Session-only preview · no audit service connected</small><button className="adm-button" disabled={!note.trim()} onClick={() => { setNotes([...notes, note.trim()]); setNote(""); }}>Post note</button></div></Panel></div></div>
 <div className="adm-action-bar"><Link className="adm-button" href="/admissions/applications"><ArrowLeft />Return to applications</Link><span className="adm-muted">{id}</span><button className="adm-button primary" disabled={index < 0 || index === STAGES.length - 1} onClick={() => { if (a.stage === "Documents Pending") {
        setNotice("Evidence must be formally verified before moving to Review. File selection in this preview does not verify documents.");
        return;
    } move(STAGES[index + 1]); }}>Progress to {STAGES[index + 1] || "next stage"}<ArrowRight /></button></div><Footer /></AdmissionsShell>;
}
