"use client";
import { useState, type ChangeEvent } from "react";
import { ImagePlus } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { PUPILS } from "@/lib/pupils-data";
import { Field, Pill } from "./parents-shared";
import styles from "./communication-drawer.module.css";
import { contactInitials, DEFAULT_SARAH_PHOTO_URL, type ContactEvent, type ParentContact, type PupilLink } from "@/lib/parents-data";
export function ContactDialog({contact,open,onClose,onSave}:{contact?:ParentContact;open:boolean;onClose:()=>void;onSave:(contact:ParentContact)=>void}){
  const [name,setName]=useState(contact?.name||"");const [title,setTitle]=useState(contact?.title||"Mrs");const [email,setEmail]=useState(contact?.email||"");const [mobile,setMobile]=useState(contact?.mobile||"");const [landline,setLandline]=useState(contact?.landline||"");const [address,setAddress]=useState(contact?.address||"");const [postcode,setPostcode]=useState(contact?.postcode||"");const [photoUrl,setPhotoUrl]=useState(contact?.photoUrl||(contact?.id==="sarah-turner"?DEFAULT_SARAH_PHOTO_URL:""));const [photoError,setPhotoError]=useState("");const [photoBusy,setPhotoBusy]=useState(false);const [error,setError]=useState("");
  const [linkedRecords,setLinkedRecords]=useState(contact?.links||[]);const relationships=[...new Set(linkedRecords.map(link=>link.relationship))];const priorities=[...new Set(linkedRecords.map(link=>link.priority))].sort((a,b)=>Number(a)-Number(b));const relationshipVerified=linkedRecords.length>0&&linkedRecords.every(link=>link.verification==="Verified");const priorityLabel=priorities.length===1?`Priority ${priorities[0]} Contact`:priorities.length?`Priority ${priorities.join(" / ")} Contact`:"No contact priority";const hasResponsibility=linkedRecords.some(link=>link.responsibility);const responsibilityVerified=linkedRecords.length>0&&linkedRecords.every(link=>link.responsibility&&link.verification==="Verified");const relationshipOptions=[...new Set(["Mother","Father","Grandparent","Foster carer","Guardian","Other",...linkedRecords.map(link=>link.relationship)])];const priorityOptions=[...new Set(["1","2","3",...linkedRecords.map(link=>link.priority)])];
  const updateLinkedRecord=(pupilId:string,changes:Partial<PupilLink>)=>setLinkedRecords(records=>records.map(link=>link.pupilId===pupilId?{...link,...changes}:link));
  const handlePhotoChange=async(event:ChangeEvent<HTMLInputElement>)=>{const input=event.currentTarget;const file=input.files?.[0];if(!file)return;if(!file.type.startsWith("image/")){setPhotoError("Choose an image file.");input.value="";return;}if(file.size>10*1024*1024){setPhotoError("Choose an image smaller than 10 MB.");input.value="";return;}setPhotoBusy(true);setPhotoError("");try{setPhotoUrl(await compressContactPhoto(file));}catch{setPhotoError("This image could not be read. Try a JPG, PNG or WebP file.");}finally{setPhotoBusy(false);input.value="";}};
  return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className={`parents-module pc-dialog sm:max-w-5xl ${contact?styles.drawer:""}`}><DialogHeader><DialogTitle>{contact?"Edit contact details":"Add parent / carer"}</DialogTitle><DialogDescription>Maintain one contact record, then link it to each pupil. Fields marked * are required.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(!name.trim()||(!email.trim()&&!mobile.trim())){setError("Enter a name and at least one email address or mobile number.");return;}if(photoBusy)return;try{onSave({...contact,id:contact?.id||`contact-${crypto.randomUUID()}`,name:name.trim(),title,email:email.trim(),mobile:mobile.trim(),landline,address:address.trim(),postcode:postcode.trim().toUpperCase(),photoUrl:photoUrl||undefined,portal:contact?.portal||"Not invited",mobileVerified:contact?.mobile===mobile&&contact.mobileVerified||false,lastLogin:contact?.lastLogin||"Never",employer:contact?.employer||"Not recorded",links:contact?linkedRecords:[],events:contact?.events||[]});onClose();}catch{setError("The contact could not be saved. Check that browser storage is available.");}}}>
    {contact&&<section className={styles.contactStatusEditor} aria-label="Linked pupil contact status editor"><div className={styles.contactStatuses} aria-label="Contact status"><Pill tone={relationshipVerified?"success":"warning"}>{linkedRecords.length?`${relationshipVerified?"Verified Parent":"Parent Verification Needed"} (${relationships.join(", ")})`:"No linked pupils"}</Pill><Pill tone={priorities.includes("1")?"info":"neutral"}>{priorityLabel}</Pill><Pill tone={responsibilityVerified?"success":hasResponsibility?"warning":"neutral"}>{responsibilityVerified?"Parental Responsibility (PR) Verified":hasResponsibility?"Parental Responsibility (PR) Needs Review":"No Parental Responsibility Recorded"}</Pill></div></section>}
    <div className={styles.formScrollArea}>
      <div className={styles.photoUpload}><div className={styles.photoPreview}>{photoUrl?<img src={photoUrl} alt={`${name||"Contact"} photo preview`}/>:<span aria-label={`${contactInitials(name||"Parent contact")} initials`}>{contactInitials(name||"Parent contact")}</span>}</div><div className={styles.photoControls}><label className={`pc-button ${styles.photoButton}`}><ImagePlus aria-hidden="true"/>Upload photo<input className={styles.fileInput} type="file" accept="image/*" aria-label="Upload contact photo" onChange={handlePhotoChange}/></label><small>Image is resized before being saved in this browser.Max allowed file size 2MB.</small>{photoBusy&&<small role="status">Processing image…</small>}{photoError&&<small className={styles.photoError} role="alert">{photoError}</small>}</div></div>
      <div className="pc-fields"><Field label="Title"><select value={title} onChange={e=>setTitle(e.target.value)}>{["Mrs","Mr","Ms","Miss","Dr","Mx","No title"].map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Full name *"><input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></Field><Field label="Email address"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></Field><Field label="Mobile number"><input type="tel" value={mobile} onChange={e=>setMobile(e.target.value)} autoComplete="tel"/></Field><Field label="Home telephone"><input type="tel" value={landline} onChange={e=>setLandline(e.target.value)}/></Field><Field label="Postcode"><input value={postcode} onChange={e=>setPostcode(e.target.value)} autoComplete="postal-code"/></Field></div><Field label="Residential address"><textarea rows={2} value={address} onChange={e=>setAddress(e.target.value)} autoComplete="street-address"/></Field>{error&&<p className="pc-notice" role="alert">{error}</p>}{contact&&<section className={styles.linkStatusEditor} aria-label="Linked pupil status editor">{linkedRecords.length>0&&<div className={styles.linkEditors}>{linkedRecords.map(link=>{const pupil=PUPILS.find(item=>item.id===link.pupilId);return <fieldset className={styles.linkEditor} key={link.pupilId}><legend>{pupil?`${pupil.legalForename} ${pupil.legalSurname}`:"Linked pupil"}</legend><div className={styles.statusFields}><label className={styles.statusField}><span>Relationship</span><select value={link.relationship} onChange={event=>updateLinkedRecord(link.pupilId,{relationship:event.target.value})}>{relationshipOptions.map(option=><option key={option}>{option}</option>)}</select></label><label className={styles.statusField}><span>Contact priority</span><select value={link.priority} onChange={event=>updateLinkedRecord(link.pupilId,{priority:event.target.value})}>{priorityOptions.map(option=><option key={option} value={option}>Priority {option}</option>)}</select></label><label className={styles.statusField}><span>Parental responsibility</span><select value={link.responsibility?"held":"not-held"} onChange={event=>updateLinkedRecord(link.pupilId,{responsibility:event.target.value==="held"})}><option value="held">Held</option><option value="not-held">Not held</option></select></label><label className={styles.statusField}><span>Verification</span><select value={link.verification} onChange={event=>updateLinkedRecord(link.pupilId,{verification:event.target.value as PupilLink["verification"]})}><option value="Verified">Verified</option><option value="Pending review">Pending review</option></select></label></div></fieldset>;})}</div>}</section>}
    </div>
    <div className="pc-dialog-actions"><button type="button" className="pc-button" onClick={onClose}>Cancel</button><button className="pc-button primary" type="submit" disabled={photoBusy}>{contact?"Save changes":"Create contact"}</button></div></form></DialogContent></Dialog>;
}
function compressContactPhoto(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error("Unable to read image"));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error("Unable to decode image"));image.onload=()=>{const maxSize=512;const ratio=Math.min(1,maxSize/Math.max(image.naturalWidth,image.naturalHeight));const width=Math.max(1,Math.round(image.naturalWidth*ratio));const height=Math.max(1,Math.round(image.naturalHeight*ratio));const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const context=canvas.getContext("2d");if(!context){reject(new Error("Canvas is unavailable"));return;}context.fillStyle="#ffffff";context.fillRect(0,0,width,height);context.drawImage(image,0,0,width,height);resolve(canvas.toDataURL("image/jpeg",0.82));};image.src=String(reader.result);};reader.readAsDataURL(file);});}
export function CommunicationDialog({contacts,kind,open,onClose,onSave}:{contacts:ParentContact[];kind:ContactEvent["kind"];open:boolean;onClose:()=>void;onSave:(event:ContactEvent)=>void}){
  const [title,setTitle]=useState("");const [body,setBody]=useState("");const [error,setError]=useState("");
  return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className={`parents-module pc-dialog sm:max-w-xl ${kind==="Email draft"?styles.drawer:""}`}><DialogHeader><DialogTitle>{kind==="Email draft"?"Compose communication draft":kind==="Call"?"Log a telephone call":"Add contact note"}</DialogTitle><DialogDescription>{kind==="Email draft"?"Save a local draft for review. This preview does not send messages.":"Record a note in this browser’s demonstration contact history."}</DialogDescription></DialogHeader><div className="pc-recipient-list"><strong>{contacts.length===1?contacts[0].name:`${contacts.length} selected contacts`}</strong><span>{contacts.map(c=>c.name).join(", ")}</span></div><form onSubmit={e=>{e.preventDefault();if(!title.trim()||!body.trim())return;try{onSave({id:crypto.randomUUID(),kind,title:title.trim(),body:body.trim(),date:new Date().toISOString()});onClose();}catch{setError("Unable to save. Browser storage may be full.");}}}><Field label={kind==="Email draft"?"Subject *":"Summary *"}><input required value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label={kind==="Email draft"?"Message *":"Details *"}><textarea required rows={6} value={body} onChange={e=>setBody(e.target.value)}/></Field>{error&&<p className="pc-notice" role="alert">{error}</p>}<div className="pc-dialog-actions"><button type="button" className="pc-button" onClick={onClose}>Cancel</button><button type="submit" className="pc-button primary">{kind==="Email draft"?"Save draft":"Save record"}</button></div></form></DialogContent></Dialog>;
}
