"use client";
import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field } from "./parents-shared";
import type { ContactEvent, ParentContact } from "@/lib/parents-data";
export function ContactDialog({contact,open,onClose,onSave}:{contact?:ParentContact;open:boolean;onClose:()=>void;onSave:(contact:ParentContact)=>void}){
  const [name,setName]=useState(contact?.name||"");const [title,setTitle]=useState(contact?.title||"Mrs");const [email,setEmail]=useState(contact?.email||"");const [mobile,setMobile]=useState(contact?.mobile||"");const [landline,setLandline]=useState(contact?.landline||"");const [address,setAddress]=useState(contact?.address||"");const [postcode,setPostcode]=useState(contact?.postcode||"");const [error,setError]=useState("");
  return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="parents-module pc-dialog sm:max-w-xl"><DialogHeader><DialogTitle>{contact?"Edit contact details":"Add parent / carer"}</DialogTitle><DialogDescription>Maintain one contact record, then link it to each pupil. Fields marked * are required.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(!name.trim()||(!email.trim()&&!mobile.trim())){setError("Enter a name and at least one email address or mobile number.");return;}try{onSave({...contact,id:contact?.id||`contact-${crypto.randomUUID()}`,name:name.trim(),title,email:email.trim(),mobile:mobile.trim(),landline,address:address.trim(),postcode:postcode.trim().toUpperCase(),portal:contact?.portal||"Not invited",mobileVerified:contact?.mobile===mobile&&contact.mobileVerified||false,lastLogin:contact?.lastLogin||"Never",employer:contact?.employer||"Not recorded",links:contact?.links||[],events:contact?.events||[]});onClose();}catch{setError("The contact could not be saved. Check that browser storage is available.");}}}><div className="pc-fields"><Field label="Title"><select value={title} onChange={e=>setTitle(e.target.value)}>{["Mrs","Mr","Ms","Miss","Dr","Mx","No title"].map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Full name *"><input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></Field><Field label="Email address"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></Field><Field label="Mobile number"><input type="tel" value={mobile} onChange={e=>setMobile(e.target.value)} autoComplete="tel"/></Field><Field label="Home telephone"><input type="tel" value={landline} onChange={e=>setLandline(e.target.value)}/></Field><Field label="Postcode"><input value={postcode} onChange={e=>setPostcode(e.target.value)} autoComplete="postal-code"/></Field></div><Field label="Residential address"><textarea rows={2} value={address} onChange={e=>setAddress(e.target.value)} autoComplete="street-address"/></Field>{error&&<p className="pc-notice" role="alert">{error}</p>}<div className="pc-dialog-actions"><button type="button" className="pc-button" onClick={onClose}>Cancel</button><button className="pc-button primary" type="submit">{contact?"Save changes":"Create contact"}</button></div></form></DialogContent></Dialog>;
}
export function CommunicationDialog({contacts,kind,open,onClose,onSave}:{contacts:ParentContact[];kind:ContactEvent["kind"];open:boolean;onClose:()=>void;onSave:(event:ContactEvent)=>void}){
  const [title,setTitle]=useState("");const [body,setBody]=useState("");const [error,setError]=useState("");
  return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="parents-module pc-dialog sm:max-w-xl"><DialogHeader><DialogTitle>{kind==="Email draft"?"Compose communication draft":kind==="Call"?"Log a telephone call":"Add contact note"}</DialogTitle><DialogDescription>{kind==="Email draft"?"Save a local draft for review. This preview does not send messages.":"Record a note in this browser’s demonstration contact history."}</DialogDescription></DialogHeader><div className="pc-recipient-list"><strong>{contacts.length===1?contacts[0].name:`${contacts.length} selected contacts`}</strong><span>{contacts.map(c=>c.name).join(", ")}</span></div><form onSubmit={e=>{e.preventDefault();if(!title.trim()||!body.trim())return;try{onSave({id:crypto.randomUUID(),kind,title:title.trim(),body:body.trim(),date:new Date().toISOString()});onClose();}catch{setError("Unable to save. Browser storage may be full.");}}}><Field label={kind==="Email draft"?"Subject *":"Summary *"}><input required value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label={kind==="Email draft"?"Message *":"Details *"}><textarea required rows={6} value={body} onChange={e=>setBody(e.target.value)}/></Field>{error&&<p className="pc-notice" role="alert">{error}</p>}<div className="pc-dialog-actions"><button type="button" className="pc-button" onClick={onClose}>Cancel</button><button type="submit" className="pc-button primary">{kind==="Email draft"?"Save draft":"Save record"}</button></div></form></DialogContent></Dialog>;
}
