"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, GraduationCap, ShieldCheck, Search, Mail, Phone, Link2, Save, Eye, EyeOff, LockKeyhole, Users, CheckCircle2 } from "lucide-react";
import { PUPILS } from "@/lib/pupils-data";
import { defaultLink, type ParentContact, type PupilLink } from "@/lib/parents-data";
import { useParents } from "./parents-store";
import { Field, LoadingContacts, Panel, ParentsFooter, ParentsShell, PersonAvatar, Pill } from "./parents-shared";
import { ContactDialog } from "./contact-dialogs";
const STEPS=["Select contact","Choose pupils","Rights & legal PR","Routing & consents","Review & confirm"];
const RESTRICTIONS=["No restrictions recorded","Prohibited steps order","Specific issue order","Supervised contact only"];
const DRAFT_KEY="school-parent-link-draft-v1";
export function LinkParentForm({parentId,pupilId}:{parentId?:string;pupilId?:string}){
  const {contacts,save,ready}=useParents();if(!ready)return <ParentsShell current="Link parent / carer"><LoadingContacts/></ParentsShell>;
  return <LinkEditor key={`${parentId||"new"}-${pupilId||"new"}`} contacts={contacts} save={save} parentId={parentId} pupilId={pupilId}/>;
}
function LinkEditor({contacts,save,parentId,pupilId}:{contacts:ParentContact[];save:(next:ParentContact[])=>void;parentId?:string;pupilId?:string}){
  const initial=contacts.find(c=>c.id===parentId);const existing=initial?.links.find(l=>l.pupilId===pupilId);const initialPupil=PUPILS.find(p=>p.id===pupilId);const [contactId,setContactId]=useState(initial?.id||"");const [selected,setSelected]=useState<string[]>(initialPupil?[initialPupil.id]:[]);const [values,setValues]=useState<PupilLink>(existing||defaultLink());const [step,setStep]=useState(initial&&initialPupil?2:initial?1:0);const [query,setQuery]=useState("");const [contactQuery,setContactQuery]=useState("");const [notice,setNotice]=useState("");const [declaration,setDeclaration]=useState(false);const [pin,setPin]=useState("");const [challenge,setChallenge]=useState("");const [showPin,setShowPin]=useState(false);const [add,setAdd]=useState(false);const formRef=useRef<HTMLFormElement>(null);const router=useRouter();
  const contact=contacts.find(c=>c.id===contactId);const pupils=PUPILS.filter(p=>selected.includes(p.id));const pupilLabel=pupils.length===1?`${pupils[0].legalForename} ${pupils[0].legalSurname}`:`${pupils.length} selected pupils`;const siblingIds=[...new Set(pupils.flatMap(p=>p.siblingIds||[]))].filter(id=>!selected.includes(id));
  const set=<K extends keyof PupilLink>(key:K,value:PupilLink[K])=>{setValues(v=>({...v,[key]:value}));setDeclaration(false);};
  const pickContact=(id:string)=>{setContactId(id);setSelected([]);setValues(defaultLink());setDeclaration(false);};
  const togglePupil=(id:string)=>{setSelected(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);if(!selected.length){const prior=contact?.links.find(l=>l.pupilId===id);setValues(prior||defaultLink(id));}setDeclaration(false);};
  const validate=()=>{
    if(!contact){setNotice("Select a parent or carer before continuing.");setStep(0);return false;}
    if(step>=1&&!selected.length){setNotice("Select at least one pupil to link.");setStep(1);return false;}
    if(!formRef.current?.reportValidity())return false;
    return true;
  };
  const next=()=>{if(validate()){setStep(s=>Math.min(4,s+1));setNotice("");window.scrollTo({top:0,behavior:"instant"});}};
  const saveDraft=()=>{try{localStorage.setItem(DRAFT_KEY,JSON.stringify({contactId,selected,values,step}));setNotice("Relationship draft saved in this browser. Collection challenge fields are not stored.");}catch{setNotice("Unable to save the draft. Check browser storage.");}};
  const restore=()=>{try{const raw=localStorage.getItem(DRAFT_KEY);if(!raw){setNotice("There is no saved relationship draft.");return;}const d=JSON.parse(raw);if(!contacts.some(c=>c.id===d.contactId)||!Array.isArray(d.selected)||!d.values||typeof d.values.relationship!=="string")throw Error();setContactId(d.contactId);setSelected(d.selected.filter((id:string)=>PUPILS.some(p=>p.id===id)));setValues({...defaultLink(),...d.values});setStep(Math.min(4,Math.max(0,Number(d.step)||0)));setDeclaration(false);setPin("");setChallenge("");setNotice("Draft restored. Check the relationship details before confirming.");}catch{setNotice("This draft could not be restored. Select a contact and pupil to start again.");}};
  const confirm=()=>{if(!validate()||!contact)return;if(!selected.length){setStep(1);return;}if(values.basis!=="Awaiting evidence"&&!values.inspectionDate){setStep(2);setNotice("Enter the document inspection date, or choose Awaiting evidence.");return;}if(!declaration){setNotice("Confirm that you have reviewed the selected pupils and permissions.");return;}try{const links=selected.map(pupilId=>({...values,pupilId,verification:"Pending review" as const}));save(contacts.map(c=>c.id===contactId?{...c,links:[...c.links.filter(l=>!selected.includes(l.pupilId)),...links],events:[{id:crypto.randomUUID(),kind:"Relationship" as const,title:`Pupil relationship${selected.length>1?"s":""} updated`,body:`${pupils.map(p=>`${p.legalForename} ${p.legalSurname}`).join(", ")} · ${values.relationship} · Priority ${values.priority}. Awaiting verification.`,date:new Date().toISOString()},...c.events]}:c));localStorage.removeItem(DRAFT_KEY);router.push(`/parents-and-carers/${contactId}`);}catch{setNotice("The pupil links could not be saved. Check browser storage and try again.");}};
  return <ParentsShell current="Link parent / carer to pupil"><header className="pc-page-heading"><div><h1 className="pc-link-title">Link Parent / Carer to Pupil Record</h1><p>Establish pupil relationships, parental responsibility, contact priority and emergency notification preferences.</p></div><Pill tone="brand"><ShieldCheck/>Relationship review</Pill></header><nav className="pc-stepper" aria-label="Linking steps">{STEPS.map((s,i)=><button key={s} type="button" aria-current={step===i?"step":undefined} disabled={i>step} onClick={()=>{setStep(i);setDeclaration(false);}}><span>{i<step?<Check/>:i+1}</span><div><small>{i===step?"Active step":`Step ${i+1}`}</small>{i===0&&contact?contact.name:i===1&&selected.length?pupilLabel:s}</div></button>)}</nav>{notice&&<div className="pc-notice" role="status">{notice}</div>}
  <div className="pc-link-layout"><aside className="pc-stack"><Panel title="Target Contact" icon={<Users/>} aside={contact?<Pill tone="info">Selected contact</Pill>:undefined}>{contact?<><div className="pc-person"><PersonAvatar name={contact.name}/><div><strong>{contact.title!=="No title"?`${contact.title} `:""}{contact.name}</strong><small>{contact.id==="sarah-turner"?"Contact ID: PAR-88204":contact.id}</small></div></div><p className="pc-icon-line pc-muted"><Mail/>{contact.email||"Email not recorded"}</p><p className="pc-icon-line pc-muted"><Phone/>{contact.mobile||"Mobile not recorded"}</p><div className="pc-soft-block"><small>Registered primary address</small><strong>{contact.links.some(l=>l.restriction!=="No restrictions recorded")?"Address restricted":`${contact.address||"Not recorded"} ${contact.postcode}`}</strong></div></>:<p className="pc-muted">Select an existing parent or carer to begin.</p>}</Panel><Panel title="Linked Pupil(s)" icon={<GraduationCap/>} aside={<Pill tone="brand">{selected.length} selected</Pill>}>{pupils.map(p=><div className="pc-selected-pupil" key={p.id}><PersonAvatar name={`${p.legalForename} ${p.legalSurname}`}/><div><strong>{p.legalForename} {p.legalSurname}</strong><small>{p.yearGroup} · Form {p.form} · {p.house}</small><small>UPN: {p.upn}</small></div><Pill tone="success">On roll</Pill></div>)}{!selected.length&&<p className="pc-muted">Choose the pupil records to associate.</p>}{siblingIds.map(id=>{const p=PUPILS.find(p=>p.id===id);return p?<div className="pc-sibling-prompt" key={id}><strong><Users/>Household sibling available</strong><p>{p.legalForename} {p.legalSurname} ({p.yearGroup}, Form {p.form}) is linked as a sibling in the existing pupil record.</p><button className="pc-button" onClick={()=>{setSelected([...selected,p.id]);setDeclaration(false);}}><Link2/>Include {p.legalForename}</button></div>:null;})}<button type="button" className="pc-button full" disabled={!contact} onClick={()=>setStep(1)}><Search/>Search &amp; link another pupil</button><div className="pc-soft-block"><ShieldCheck/><p>Keep relationship permissions specific to each pupil. Review supporting evidence before confirming changes.</p></div></Panel><button className="pc-text-button" onClick={restore}>Restore saved draft</button></aside>
  <form className="pc-stack pc-link-form" ref={formRef} onSubmit={e=>{e.preventDefault();if(step===4)confirm();else next();}}>
  {step===0&&<Panel title="Select a Parent / Carer" icon={<Users/>}><p className="pc-section-description">Search existing contacts to avoid creating duplicate family records.</p><label className="pc-search"><Search/><input aria-label="Search existing contacts" value={contactQuery} onChange={e=>setContactQuery(e.target.value)} placeholder="Search name or email…"/></label><div className="pc-picker-list">{contacts.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(contactQuery.toLowerCase())).map(c=><label className="pc-picker-option" key={c.id}><input type="radio" name="contact" checked={contactId===c.id} onChange={()=>pickContact(c.id)}/><PersonAvatar name={c.name}/><span><strong>{c.name}</strong><small>{c.email||c.mobile}</small></span><Pill>{c.links.length} pupils</Pill></label>)}{!contacts.some(c=>`${c.name} ${c.email}`.toLowerCase().includes(contactQuery.toLowerCase()))&&<p className="pc-empty">No contacts found.</p>}</div><button className="pc-button" type="button" onClick={()=>setAdd(true)}>Add a new parent / carer</button></Panel>}
  {step===1&&<Panel title="Choose Pupil Records" icon={<GraduationCap/>}><p className="pc-section-description">Select one or more pupils. Existing associations will be updated, not duplicated.</p><label className="pc-search"><Search/><input aria-label="Search pupils to link" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pupil name, form or UPN…"/></label><div className="pc-picker-list">{PUPILS.filter(p=>`${p.legalForename} ${p.legalSurname} ${p.form} ${p.upn}`.toLowerCase().includes(query.toLowerCase())).map(p=><label className="pc-picker-option" key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>togglePupil(p.id)}/><PersonAvatar name={`${p.legalForename} ${p.legalSurname}`}/><span><strong>{p.legalForename} {p.legalSurname}</strong><small>{p.yearGroup} · {p.form} · UPN {p.upn}</small></span><Pill tone={contact?.links.some(l=>l.pupilId===p.id)?"info":"neutral"}>{contact?.links.some(l=>l.pupilId===p.id)?"Existing link":"Available"}</Pill></label>)}</div>{!PUPILS.some(p=>`${p.legalForename} ${p.legalSurname} ${p.form} ${p.upn}`.toLowerCase().includes(query.toLowerCase()))&&<p className="pc-empty">No pupils match your search.</p>}</Panel>}
  {step===2&&<>{selected.length>1&&<p className="pc-notice">These relationship and routing settings will apply to all {selected.length} selected pupils. Review them individually if their arrangements differ.</p>}<Panel title="1. Relationship Definition & Cohabitation" aside={<Pill>Contact relationship</Pill>}><div className="pc-fields"><Field label={`Relationship to ${pupilLabel} *`}><select required value={values.relationship} onChange={e=>set("relationship",e.target.value)}>{["Mother","Father","Grandparent","Foster carer","Guardian","Other"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Relationship verification basis"><select value={values.basis} onChange={e=>set("basis",e.target.value)}>{["Awaiting evidence","Birth certificate","Adoption certificate","Court documentation","Local authority documentation","Other supporting evidence"].map(v=><option key={v}>{v}</option>)}</select></Field></div><fieldset className="pc-fieldset"><legend>Cohabitation status</legend><div className="pc-radio-grid">{[["Lives with pupil","Pupil resides at the main address"],["Split residence","Shared residence or joint custody home"],["Does not cohabit","Non-resident parent or guardian"]].map(([v,sub])=><label className="pc-radio-card" key={v}><input type="radio" name="residence" checked={values.residence===v} onChange={()=>set("residence",v)}/><span>{v}<small>{sub}</small></span></label>)}</div></fieldset></Panel>
  <Panel title="2. Parental Responsibility & Legal Orders" icon={<ShieldCheck/>}><div className="pc-responsibility-question"><div><strong>Does this individual hold parental responsibility?</strong><p>Record the status supported by the pupil’s documents. Changes will remain pending review.</p></div><div className="pc-toggle" role="group" aria-label="Parental responsibility"><button type="button" aria-pressed={values.responsibility} onClick={()=>set("responsibility",true)}>Yes — holds PR</button><button type="button" aria-pressed={!values.responsibility} onClick={()=>set("responsibility",false)}>No</button></div></div><div className="pc-fields"><Field label="Legal documentation category"><input value={values.basis} readOnly/></Field><Field label={`Document inspection date${values.basis!=="Awaiting evidence"?" *":""}`} hint="Record when the supporting evidence was checked."><input type="date" required={values.basis!=="Awaiting evidence"} value={values.inspectionDate} onChange={e=>set("inspectionDate",e.target.value)}/></Field></div><fieldset className="pc-fieldset"><legend>Court orders or restrictions in force</legend><div className="pc-restriction-grid">{RESTRICTIONS.map(v=><label className="pc-radio-card" key={v}><input type="radio" name="restriction" checked={values.restriction===v} onChange={e=>{set("restriction",v);if(e.target.checked&&v!=="No restrictions recorded")set("collection","Not authorised");}}/><span>{v}</span></label>)}</div></fieldset>{values.restriction!=="No restrictions recorded"&&<div className="pc-warning"><LockKeyhole/><p>Restriction recorded. Check the supporting order before authorising collection or changing correspondence preferences.</p></div>}</Panel>
  <Panel title="3. Contact Priority & Notification Routing" aside={<Pill>Emergency call order</Pill>}><div className="pc-fields"><Field label="Contact priority ranking *" hint="Determines the order shown to staff during an emergency."><select value={values.priority} onChange={e=>set("priority",e.target.value)}><option value="1">Priority 1 — first contact</option><option value="2">Priority 2 — secondary contact</option><option value="3">Priority 3 — additional / emergency</option></select></Field><label className="pc-check-card"><input type="checkbox" checked={values.emergency} onChange={e=>set("emergency",e.target.checked)}/><span>Emergency notification contact<small>Include in the pupil’s emergency contact chain.</small></span></label></div><fieldset className="pc-fieldset"><legend>Pupil communication preferences</legend><div className="pc-check-grid">{([["reports","Academic reports & school correspondence","Progress reports, exam timetables and school letters."],["attendance","Attendance & absence alerts","Registration notifications and lateness alerts."],["behaviour","Behaviour, detentions & merits","Conduct updates and pastoral correspondence."],["finance","Finance & cashless catering","School meal balances, lesson charges and trips."]] as const).map(([key,title,sub])=><label className="pc-check-card" key={key}><input type="checkbox" checked={values[key]} onChange={e=>set(key,e.target.checked)}/><span>{title}<small>{sub}</small></span></label>)}</div></fieldset></Panel>
  <Panel title="4. Collection Authorisation & Identity Check" icon={<LockKeyhole/>}><div className="pc-fields"><Field label="Authorised to collect from school"><select value={values.collection} onChange={e=>set("collection",e.target.value)}>{["Authorised","Supervised collection","Not authorised"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Collection PIN — session preview" hint="Optional four-digit demo PIN; not saved."><div className="pc-password"><input type={showPin?"text":"password"} inputMode="numeric" pattern="[0-9]{4}" maxLength={4} placeholder="4-digit demo PIN" value={pin} onChange={e=>setPin(e.target.value)}/><button className="pc-icon-button" type="button" aria-label={showPin?"Hide collection PIN":"Show collection PIN"} onClick={()=>setShowPin(!showPin)}>{showPin?<EyeOff/>:<Eye/>}</button></div></Field></div><Field label="Telephone identity challenge — session preview"><input value={challenge} onChange={e=>setChallenge(e.target.value)} placeholder="Optional demonstration challenge"/></Field><div className="pc-info"><LockKeyhole/><p>This design preview does not store collection PINs or identity challenges. Only the collection authorisation is saved.</p></div></Panel></>}
  {step===3&&<Panel title="Routing & Consent Review" icon={<ClipboardIcon/>}><p className="pc-section-description">Check which notifications this contact should receive for the selected pupils.</p><div className="pc-review-facts"><div><small>Emergency contact order</small><strong>Priority {values.priority}</strong></div><div><small>Emergency notifications</small><strong>{values.emergency?"Included":"Not included"}</strong></div><div><small>Collection authorisation</small><strong>{values.collection}</strong></div><div><small>Parental responsibility</small><strong>{values.responsibility?"Recorded as held":"Not held"}</strong></div></div><div className="pc-consents">{([["Academic reports",values.reports],["Attendance & absence",values.attendance],["Behaviour & pastoral",values.behaviour],["Finance & catering",values.finance]] as const).map(([label,on])=><div key={label}><CheckCircle2/><strong>{label}</strong><Pill tone={on?"success":"neutral"}>{on?"Included":"Not included"}</Pill></div>)}</div><div className="pc-info"><ShieldCheck/><p>Communication preferences are recorded per pupil. They do not create signed consent forms or verify legal documentation.</p></div><button className="pc-button" type="button" onClick={()=>setStep(2)}>Edit relationship &amp; routing</button></Panel>}
  {step===4&&<Panel title="Review & Confirm Association" icon={<Link2/>}><p className="pc-section-description">Confirm the contact, pupils and permissions before saving the relationship.</p><div className="pc-review-facts"><div><small>Parent / carer</small><strong>{contact?.name}</strong></div><div><small>Relationship</small><strong>{values.relationship}</strong></div><div><small>Contact priority</small><strong>Priority {values.priority}</strong></div><div><small>Parental responsibility</small><strong>{values.responsibility?"Held — pending review":"Not held"}</strong></div><div><small>Residence</small><strong>{values.residence}</strong></div><div><small>Restrictions</small><strong>{values.restriction}</strong></div></div>{pupils.map(p=><div className="pc-confirm-pupil" key={p.id}><GraduationCap/><strong>{p.legalForename} {p.legalSurname}</strong><span>{p.yearGroup} · {p.form}</span><Pill tone="info">{contact?.links.some(l=>l.pupilId===p.id)?"Update existing link":"New association"}</Pill></div>)}<label className="pc-declaration"><input type="checkbox" required checked={declaration} onChange={e=>setDeclaration(e.target.checked)}/><span>I have reviewed the selected pupils, relationship, contact priority and permissions. I understand that this local record remains pending verification. *</span></label><div className="pc-info"><ShieldCheck/><p>Saving records the association and a local history entry. It does not grant access to a connected portal or send any notification.</p></div></Panel>}
  <div className="pc-form-actions"><button className="pc-button" type="button" onClick={()=>step>0?setStep(step-1):router.push("/parents-and-carers")}><ArrowLeft/>{step?"Back":"Cancel"}</button><button className="pc-button" type="button" onClick={saveDraft}><Save/>Save draft</button><button className="pc-button primary" type="submit">{step===4?"Confirm & link contact":"Continue"}{step===4?<CheckCircle2/>:<ArrowRight/>}</button></div></form></div><ParentsFooter/>
  {add&&<ContactDialog open onClose={()=>setAdd(false)} onSave={c=>{save([...contacts,c]);pickContact(c.id);setStep(1);}}/>}
  </ParentsShell>;
}
function ClipboardIcon(){return <ShieldCheck/>;}
